{-# OPTIONS -Wall -fno-warn-missing-signatures #-}
module Targets.SeeReason (targets) where

import qualified Debian.AutoBuilder.Params as P
import Targets.Common

targets _home =
    [ P.Package { P.name = "autobuilder"
                , P.spec = "darcs:http://src.seereason.com/autobuilder"
                , P.flags = [] }
    , P.Package { P.name = "happstack-debianization"
                , P.spec = "darcs:http://src.seereason.com/happstack-debianization"
                , P.flags = [] }
    , P.Package { P.name = "haskell-agi"
                , P.spec="darcs:http://src.seereason.com/haskell-agi"
                , P.flags = [] }
    , P.Package { P.name = "haskell-archive"
                , P.spec = "darcs:http://src.seereason.com/archive"
                , P.flags = [] }
    , P.Package { P.name = "haskell-consumer"
                , P.spec = "darcs:http://src.seereason.com/haskell-consumer"
                , P.flags = [] }
    , P.Package { P.name = "haskell-debian-mirror"
                , P.spec = "darcs:http://src.seereason.com/mirror"
                , P.flags = [] }
    , P.Package { P.name = "haskell-debian-repo"
                , P.spec = "darcs:http://src.seereason.com/haskell-debian-repo"
                , P.flags = [] }
    , P.Package { P.name = "haskell-decimal"
                , P.spec = "darcs:http://src.seereason.com/decimal"
                , P.flags = [] }
    , P.Package { P.name = "haskell-digestive-functors-hsp"
                , P.spec = "darcs:" ++ repo ++ "/digestive-functors-hsp"
                , P.flags = [] }
    , P.Package { P.name = "haskell-extra"
                , P.spec = "darcs:http://src.seereason.com/haskell-extra"
                , P.flags = [P.RelaxDep "cabal-debian"] }
    , P.Package { P.name = "haskell-formlets-hsp"
                , P.spec = "darcs:" ++ repo ++ "/formlets-hsp"
                , P.flags = [] }
    , P.Package { P.name = "haskell-frisby"
                , P.spec = "deb-dir:(cd:frisby:darcs:http://src.seereason.com/frisby):(darcs:http://src.seereason.com/frisby-debian)"
                , P.flags = [] }
    , P.Package { P.name = "haskell-happstack-authenticate"
                , P.spec = "darcs:" ++ repo ++ "/happstack-authenticate"
                , P.flags = [] }
    , P.Package { P.name = "haskell-happstackdotcom"
                , P.spec = "darcs:http://patch-tag.com/r/stepcut/happstackDotCom"
                , P.flags = [] }
    , P.Package { P.name = "haskell-happstackdotcom-doc"
                , P.spec = "darcs:http://src.seereason.com/happstackDotCom-doc"
                , P.flags = [] }
    , P.Package { P.name = "haskell-happstack-extra"
                , P.spec = "darcs:" ++ repo ++ "/happstack-extra"
                , P.flags = [] }
    , P.Package { P.name = "haskell-happstack-facebook"
                , P.spec = "darcs:" ++ repo ++ "/happstack-facebook"
                , P.flags = [] }
    , P.Package { P.name = "haskell-happstack-hsp"
                , P.spec = "deb-dir:(cd:happstack-hsp:darcs:" ++ happstackRepo ++ "):(darcs:" ++ repo ++ "/happstack-hsp-debian)"
                , P.flags = [] }
    , P.Package{ P.name = "haskell-acid-state"
              , P.spec = "deb-dir:(darcs:http://src.seereason.com/acid-state):(darcs:http://src.seereason.com/haskell-acid-state-debian)"
              , P.flags = []
            }
    , P.Package { P.name = "haskell-help"
                , P.spec = "darcs:http://src.seereason.com/haskell-help"
                , P.flags = [] }
    , P.Package { P.name = "haskell-hinotify"
             -- , P.spec = "deb-dir:(darcs:http://haskell.org/~kolmodin/code/hinotify):(darcs:http://src.seereason.com/hinotify-debian)"
                , P.spec = "deb-dir:(darcs:http://src.seereason.com/hinotify):(darcs:http://src.seereason.com/hinotify-debian)"
                , P.flags = [] }
    , P.Package { P.name = "haskell-hsx-jmacro"
                , P.spec = "deb-dir:(cd:hsx-jmacro:darcs:" ++ happstackRepo ++ "):(darcs:" ++ repo ++ "/haskell-hsx-jmacro-debian)"
                , P.flags = []
             }
    , P.Package { P.name = "haskell-html-entities"
                , P.spec = "darcs:http://src.seereason.com/html-entities"
                , P.flags = [] }
    , P.Package { P.name = "haskell-iconv"
                , P.spec = "darcs:http://src.seereason.com/iconv"
                , P.flags = [] }
    , P.Package { P.name = "haskell-logic"
                , P.spec = "darcs:http://src.seereason.com/haskell-logic"
                , P.flags = [] }
    , P.Package { P.name = "haskell-mime"
                , P.spec = "darcs:http://src.seereason.com/haskell-mime"
                , P.flags = [] }
    , P.Package { P.name = "haskell-proplogic"
                , P.spec="deb-dir:(uri:http://www.bucephalus.org/PropLogic/PropLogic-0.9.tar.gz:e2fb3445dd16d435e81d7630d7f78c01):(darcs:http://src.seereason.com/haskell-proplogic-debian)"
                , P.flags = [] }
    , P.Package { P.name = "haskell-revision"
                , P.spec = "darcs:http://src.seereason.com/haskell-revision"
                , P.flags = [] }
    , P.Package { P.name = "haskell-unixutils"
                , P.spec = "darcs:" ++ repo ++ "/haskell-unixutils"
                , P.flags = [] }
    , P.Package { P.name = "haskell-web-routes-happstack"
                , P.spec = "cd:web-routes-happstack:darcs:" ++ repo ++ "/web-routes"
                , P.flags = [] }
    , P.Package { P.name = "haskell-web-routes-mtl"
                , P.spec = "cd:web-routes-mtl:darcs:" ++ repo ++ "/web-routes"
                , P.flags = [] }      
    , P.Package { P.name = "haskell-web-routes"
                , P.spec = "cd:web-routes:darcs:" ++ repo ++ "/web-routes"
                , P.flags = [] }
    , P.Package { P.name = "haskell-web-routes-hsp"
                , P.spec = "cd:web-routes-hsp:darcs:" ++ repo ++ "/web-routes"
                , P.flags = [] }
    , P.Package { P.name = "haskell-web-routes-th"
                , P.spec = "cd:web-routes-th:darcs:" ++ repo ++ "/web-routes"
                , P.flags = [] }
    , P.Package { P.name = "seereason-keyring"
                , P.spec = "darcs:http://src.seereason.com/seereason-keyring"
                , P.flags = [] }
    , P.Package { P.name = "vc-darcs"
                , P.spec = "darcs:http://src.seereason.com/vc-darcs"
                , P.flags = [] }
    ]
