{-# OPTIONS -Wall -fno-warn-missing-signatures #-}
module Targets.Sid ( sidRing0, sidRing1, sidWaiting, nonHaskell ) where

import Debian.AutoBuilder.ParamClass (Target(..))

repo = "http://src.seereason.com"
localRepo home = "file://" ++ home ++ "/darcs"

sidRing0 home =
    [ Target { sourcePackageName = "ghc"
             , sourceSpec = "apt:sid:ghc"
             , relaxInfo = ["ghc"
                           ,"happy"
                           ,"alex"
                           ,"xsltproc"
                           ,"haskell-devscripts"
                           ,"debhelper"
                           ,"quilt"]
             }
    , Target { sourcePackageName = "hscolour"
             -- , sourceSpec = "quilt:(apt:sid:hscolour):(darcs:http://src.seereason.com/hscolour-quilt)"
             , sourceSpec = "apt:sid:hscolour"
             , relaxInfo = ["hscolour"] }
{-    , Target { sourcePackageName = "gmp"
             , sourceSpec = "quilt:(apt:sid:gmp):(darcs:" ++ repo ++ "/gmp-quilt)"
             , relaxInfo = [] } -}
    , Target { sourcePackageName = "haskell-dummy"
             , sourceSpec = "apt:sid:haskell-dummy"
             , relaxInfo = [] }
    -- Required by the darcs 2.3.0-3 in sid.
    , Target { sourcePackageName = "haskell-devscripts"
             , sourceSpec = "apt:sid:haskell-devscripts"
             -- , sourceSpec = "quilt:(apt:sid:haskell-devscripts):(darcs:http://src.seereason.com/haskell-devscripts-quilt)"
             -- Experimental version
             --, sourceSpec = "quilt:(darcs:http://darcs.debian.org/pkg-haskell/haskell-devscripts):(darcs:http://src.seereason.com/haskell-devscripts-quilt)"
             , relaxInfo = ["hscolour"] }
    , Target { sourcePackageName = "haskell-cpphs"
             , sourceSpec = "apt:sid:cpphs"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-transformers"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/transformers/0.2.2.0/transformers-0.2.2.0.tar.gz:3470ac66116900cd1ba84d3744474e49):(darcs:" ++ repo ++ "/haskell-transformers-debian)"
             , sourceSpec = "apt:sid:haskell-transformers"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-mtl"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/mtl/2.0.0.0/mtl-2.0.0.0.tar.gz:068e6714badedd839808ce8d7dd80abe):(darcs:http://src.seereason.com/haskell-mtl-debian)"
             , sourceSpec = "apt:sid:haskell-mtl"
             , relaxInfo = [] }
    , Target { sourcePackageName = "happy"
             , sourceSpec = "apt:sid:happy"
             , relaxInfo = ["happy"] }
    -- Version 1.11 of haskell-src-exts now sid requires changes to haskell-authenticate
    , Target { sourcePackageName = "haskell-src-exts"
             , sourceSpec = "apt:sid:haskell-src-exts"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hsx"
             , sourceSpec = "apt:sid:haskell-hsx"
             -- , sourceSpec = "deb-dir:(darcs:http://code.haskell.org/HSP/hsx):(darcs:" ++ ghcRepo ++ "/hsx-debian)"
             -- , sourceSpec = "deb-dir:(darcs:" ++ ghcRepo ++ "/hsx):(darcs:" ++ ghcRepo ++ "/hsx-debian)"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/hsx/0.9.0/hsx-0.9.0.tar.gz:d82f4ae3fcc08b4acdb001f7b189c13a):(darcs:http://src.seereason.com/hsx-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-utf8-string"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/utf8-string/0.3.6/utf8-string-0.3.6.tar.gz:be8c5ef52a0824babdc89d60c1e9b600):(darcs:http://src.seereason.com/utf8-string-debian)"
             , sourceSpec = "apt:sid:haskell-utf8-string"
             , relaxInfo = ["hscolour", "cpphs"] }
    , Target { sourcePackageName = "haskell-deepseq"
             , sourceSpec = "apt:sid:haskell-deepseq"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-text"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/text/0.11.0.5/text-0.11.0.5.tar.gz:516a6813a6b9061fabdc9f0c3bbb1592):(darcs:http://src.seereason.com/haskell-text-debian)"
             , sourceSpec = "apt:sid:haskell-text"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hjavascript"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/HJavaScript/0.4.6/HJavaScript-0.4.6.tar.gz:440ee4f0bcffe6e60ee0ce02dd3922cf):(darcs:http://src.seereason.com/hjavascript-debian)"
             , sourceSpec = "apt:sid:haskell-hjavascript"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hjscript"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/HJScript/0.5.0/HJScript-0.5.0.tar.gz:3eb1e67900e41c9e93528ae15ca27028):(darcs:http://src.seereason.com/hjscript-debian)"
             , sourceSpec = "apt:sid:haskell-hjscript"
             , relaxInfo = [] }      
    , Target { sourcePackageName = "haskell-harp"
             -- , sourceSpec = "deb-dir:(darcs:http://src.seereason.com/harp):(darcs:http://src.seereason.com/harp-debian)"
             , sourceSpec = "apt:sid:haskell-harp"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hsp"
             , sourceSpec = "apt:sid:haskell-hsp"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/hsp/0.6.0/hsp-0.6.0.tar.gz:c80d48e6706a4d1d4608f63549069c36):(darcs:http://src.seereason.com/hsp-debian)"
             , relaxInfo = [] }
    ]

sidRing1 home =
    [ Target { sourcePackageName = "darcs"
             , sourceSpec = "apt:sid:darcs"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/darcs/2.5.2/darcs-2.5.2.tar.gz:491b6ca01dec245a16112ad2c7e07dc1):(darcs:http://src.seereason.com/darcs-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "agda"
             , sourceSpec = "apt:sid:agda"
             , relaxInfo = [] }
    , Target { sourcePackageName = "agda-bin"
             , sourceSpec = "apt:sid:agda-bin"
             , relaxInfo = [] }
    , Target { sourcePackageName = "agda-stdlib"
             , sourceSpec = "apt:sid:agda-stdlib"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-attoparsec-enumerator"
             , sourceSpec = "apt:sid:haskell-attoparsec-enumerator"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/attoparsec-enumerator/0.2/attoparsec-enumerator-0.2.tar.gz:ec79f184f49109cc7ec882dfbb9b836e):(darcs:http://src.seereason.com/haskell-attoparsec-enumerator-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-attoparsec"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/attoparsec/0.8.1.1/attoparsec-0.8.1.1.tar.gz:8948e39002acb823fae3af9cde6983e8):(darcs:http://src.seereason.com/haskell-attoparsec-debian)"
             , sourceSpec = "apt:sid:haskell-attoparsec"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-base64-bytestring"
             , sourceSpec = "apt:sid:haskell-base64-bytestring"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/base64-bytestring/0.1.0.1/base64-bytestring-0.1.0.1.tar.gz:f0f9cb5a29a718bcca49e2c284378d62):(darcs:http://src.seereason.com/haskell-base64-bytestring-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-binary"
             , sourceSpec = "quilt:(apt:sid:haskell-binary):(darcs:http://src.seereason.com/haskell-binary-quilt)"
             -- , sourceSpec = "apt:sid:haskell-binary"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-blaze-builder"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/blaze-builder/0.2.1.4/blaze-builder-0.2.1.4.tar.gz:fefd5b1a72104c835034287ca4591460):(darcs:http://src.seereason.com/haskell-blaze-builder-debian)"
             , sourceSpec = "apt:sid:haskell-blaze-builder"
             , relaxInfo = [] }
    , Target{ sourcePackageName = "haskell-blaze-html"
            , sourceSpec = "apt:sid:haskell-blaze-html"
            -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/blaze-html/0.4.1.0/blaze-html-0.4.1.0.tar.gz:6aa538867ee7ede93f0377259766137e):(darcs:http://src.seereason.com/haskell-blaze-html-debian)"
            , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-blaze-builder-enumerator"
             , sourceSpec = "apt:sid:haskell-blaze-builder-enumerator"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/blaze-builder-enumerator/0.2.0.1/blaze-builder-enumerator-0.2.0.1.tar.gz:3d21f0bda0606d7639ade71dc5bcc69c):(darcs:http://src.seereason.com/haskell-blaze-builder-enumerator-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-bytestring-nums"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/bytestring-nums/0.3.2/bytestring-nums-0.3.2.tar.gz:f54377b9915a9074d8dc1a07f4f17298):(darcs:http://src.seereason.com/haskell-bytestring-nums-debian)"
             , sourceSpec = "apt:sid:haskell-bytestring-nums"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-bzlib"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/bzlib/0.5.0.0/bzlib-0.5.0.0.tar.gz:ab594aaf9998ed602f8b23dd25199e19):(darcs:http://src.seereason.com/haskell-bzlib-debian)"
             , sourceSpec = "quilt:(apt:sid:haskell-bzlib):(darcs:http://src.seereason.com/haskell-bzlib-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-cereal"
             , sourceSpec = "apt:sid:haskell-cereal"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/cereal/0.3.3.0/cereal-0.3.3.0.tar.gz:70d24b61194880df3ec798ad89a21a7b):(darcs:http://src.seereason.com/haskell-cereal-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-citeproc-hs"
             , sourceSpec = "apt:sid:haskell-citeproc-hs"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-colour"
             -- , sourceSpec="deb-dir:(uri:http://hackage.haskell.org/packages/archive/colour/2.3.1/colour-2.3.1.tar.gz:5edced36d4c27393ae1ce1389eeb25ad):(darcs:http://src.seereason.com/haskell-colour-debian)"
             , sourceSpec="apt:sid:haskell-colour"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-criterion"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/criterion/0.5.0.5/criterion-0.5.0.5.tar.gz:dddc5f8dc9dbabbd36b82a8a531b178c):(darcs:http://src.seereason.com/haskell-criterion-debian)"
             , sourceSpec = "apt:sid:haskell-criterion"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-crypto"
             , sourceSpec = "apt:sid:haskell-crypto"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/Crypto/4.2.3/Crypto-4.2.3.tar.gz:28b8556f1ea5b85e0d2a8d0d030c0f69):(darcs:http://src.seereason.com/crypto-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-crypto-api"
             , sourceSpec = "apt:sid:haskell-crypto-api"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/crypto-api/0.2/crypto-api-0.2.tar.gz:c7b7aa4459549ebc9d0936a7efdde87f):(darcs:http://src.seereason.com/haskell-crypto-api-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-cryptocipher"
             , sourceSpec = "apt:sid:haskell-cryptocipher"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/cryptocipher/0.2/cryptocipher-0.2.tar.gz:1b2353ae52c16463d841c8c76fea2b47):(darcs:http://src.seereason.com/haskell-cryptocipher-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-cryptohash"
             , sourceSpec = "apt:sid:haskell-cryptohash"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/cryptohash/0.6.1/cryptohash-0.6.1.tar.gz:40139c278620007fe7c7840050050fa3):(darcs:http://src.seereason.com/haskell-cryptohash-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-curl"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/curl/1.3.5/curl-1.3.5.tar.gz:0b08065ca25cead1e2b374958dc69818):(darcs:http://src.seereason.com/haskell-curl-debian)"
             , sourceSpec = "apt:sid:haskell-curl"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-data-accessor"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/data-accessor/0.2.1.2/data-accessor-0.2.1.2.tar.gz:8eabca77e2202dc0735b45ca7dea9175):(darcs:" ++ ghcRepo ++ "/haskell-data-accessor-debian)"
             , sourceSpec = "apt:sid:haskell-data-accessor"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-data-accessor-template"
             , sourceSpec = "apt:sid:haskell-data-accessor-template"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/data-accessor-template/0.2.1.2/data-accessor-template-0.2.1.2.tar.gz:0feb98757d889bbc9fbbe0379cdb3c05):(darcs:http://src.seereason.com/haskell-data-accessor-template-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-data-default"
             , sourceSpec = "apt:sid:haskell-data-default"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/data-default/0.2/data-default-0.2.tar.gz:cfbbaaa4fa49a0c4c1b52c5d51258ae7):(darcs:http://src.seereason.com/haskell-data-default-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-dataenc"
             , sourceSpec = "apt:sid:haskell-dataenc"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-debian"
             , sourceSpec = "apt:sid:haskell-debian"
             -- , sourceSpec = "darcs:http://src.seereason.com/haskell-debian"
             , relaxInfo = ["cabal-debian"] }
    , Target { sourcePackageName = "haskell-digest"
             , sourceSpec = "apt:sid:haskell-digest"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/digest/0.0.0.5/digest-0.0.0.5.tar.gz:ba60cc9d1ad6d0795ad84390976699d1):(darcs:http://src.seereason.com/debian/haskell-digest-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-diff"
             , sourceSpec = "apt:sid:haskell-diff"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-dlist"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/dlist/0.5/dlist-0.5.tar.gz:54f6c18ff689b7ef54e3229dc4a94107):(darcs:http://src.seereason.com/haskell-dlist-debian)"
             , sourceSpec = "apt:sid:haskell-dlist"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-edison-api"
             , sourceSpec="apt:sid:haskell-edison-api"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-edison-core"
             , sourceSpec="apt:sid:haskell-edison-core"
             -- , sourceSpec="quilt:(apt:sid:haskell-edison-core):(darcs:http://src.seereason.com/edison-core-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-enumerator"
             , sourceSpec = "apt:sid:haskell-enumerator"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/enumerator/0.4.6/enumerator-0.4.6.tar.gz:660f11852f47c8a93518c0163a9c6397):(darcs:http://src.seereason.com/haskell-enumerator-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-erf"
             -- , sourceSpec="deb-dir:(uri:http://hackage.haskell.org/packages/archive/erf/1.0.0.0/erf-1.0.0.0.tar.gz:1bdb56838565abfaa7d7ab6e2870ddaa):(darcs:http://src.seereason.com/haskell-erf-debian)"
             , sourceSpec = "apt:sid:haskell-erf"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-failure"
             , sourceSpec = "apt:sid:haskell-failure"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/failure/0.1.0/failure-0.1.0.tar.gz:7c14ad9271ec9f8f87b4fdbf63291c44):(darcs:http://src.seereason.com/haskell-failure-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-feed"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/feed/0.3.8/feed-0.3.8.tar.gz:0df089dfc2e2b0726ee5d66286d98f5f):(darcs:http://src.seereason.com/debian/haskell-feed-debian)"
             , sourceSpec = "apt:sid:haskell-feed"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-fgl"
             , sourceSpec = "apt:sid:haskell-fgl"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hashed-storage"
             , sourceSpec = "apt:sid:haskell-hashed-storage"
             -- , sourceSpec = "quilt:(apt:sid:haskell-hashed-storage):(darcs:http://src.seereason.com/hashed-storage-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-haskeline" -- Required by darcs
             -- , sourceSpec = "quilt:(apt:sid:haskell-haskeline):(darcs:" ++ repo ++ "/haskell-haskeline-quilt)"
             , sourceSpec = "apt:sid:haskell-haskeline"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-haskell-src"
             , sourceSpec = "apt:sid:haskell-haskell-src"
             , relaxInfo = [] }
    , Target { sourcePackageName = "highlighting-kate"
             , sourceSpec = "apt:sid:highlighting-kate"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hsemail"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/hsemail/1.6/hsemail-1.6.tar.gz:fa56a870e06435ccea8da0ecebdbf689):(darcs:http://src.seereason.com/debian/haskell-hsemail-debian)"
             , sourceSpec = "apt:sid:haskell-hsemail"
             , relaxInfo = [] }

    , Target { sourcePackageName = "hslogger"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/hslogger/1.0.10/hslogger-1.0.10.tar.gz:f65a5326d28f9cdad6887a32525d70dc):(darcs:http://src.seereason.com/hslogger-debian)"
             , sourceSpec = "apt:sid:hslogger"

             -- No profiling libraries in sid version
             -- , sourcePackageName = "hslogger"
             -- , sourceSpec = "apt:sid:hslogger"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hstringtemplate"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/HStringTemplate/0.4.3/HStringTemplate-0.4.3.tar.gz:57139f6695f1c268ed38c34336191636):(darcs:http://src.seereason.com/HStringTemplate-debian)"
             , sourceSpec = "apt:sid:haskell-hstringtemplate"
             , relaxInfo = [] }
{-
    , Target { sourcePackageName = "haskell-hsx-jmacro"
             , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/hsx-jmacro/6.0.2/hsx-jmacro-6.0.2.tar.gz:1f0e318b0f74bad0b3191e3acf10e89c):(darcs:http://src.seereason.com/haskell-hsx-jmacro-debian)"
             , relaxInfo = [] }
-}
    , Target { sourcePackageName = "haskell-html"
             , sourceSpec = "apt:sid:haskell-html"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-case-insensitive"
             , sourceSpec = "apt:sid:haskell-case-insensitive"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-cprng-aes"
             , sourceSpec = "apt:sid:haskell-cprng-aes"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-http-types"
             , sourceSpec = "apt:sid:haskell-http-types"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-monad-control"
             , sourceSpec = "apt:sid:haskell-monad-control"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-base-unicode-symbols"
             , sourceSpec = "apt:sid:haskell-base-unicode-symbols"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-zlib-enum"
             , sourceSpec = "apt:sid:haskell-zlib-enum"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-http"
             , sourceSpec = "apt:sid:haskell-http"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-hunit"
             , sourceSpec = "apt:sid:haskell-hunit"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-irc"
             , sourceSpec = "apt:sid:haskell-irc"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-json"
             , sourceSpec = "quilt:(apt:sid:haskell-json=0.4.4-2):(darcs:" ++ repo ++ "/haskell-json-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-largeword"
             , sourceSpec = "apt:sid:haskell-largeword"
             , relaxInfo = [] }
    , Target { sourcePackageName = "magic-haskell"
             , sourceSpec = "apt:sid:magic-haskell"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/magic/1.0.8/magic-1.0.8.tar.gz:e81c493fe185431a5b70d4855ed4b87f):(darcs:http://src.seereason.com/magic-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-maybet"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/MaybeT/0.1.2/MaybeT-0.1.2.tar.gz:9864a3f34151217004f8c968fda5b427):(darcs:http://src.seereason.com/MaybeT-debian)"
             , sourceSpec = "apt:sid:haskell-maybet"
             , relaxInfo = [] }               
    , Target { sourcePackageName = "haskell-mmap"
             , sourceSpec = "apt:sid:haskell-mmap"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-monadcatchio-mtl"
             , sourceSpec = "apt:sid:haskell-monadcatchio-mtl"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/MonadCatchIO-mtl/0.3.0.1/MonadCatchIO-mtl-0.3.0.1.tar.gz:53f56fece758b15eff950f9c9796fbdf):(darcs:http://src.seereason.com/haskell-monadcatchio-mtl-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-mwc-random"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/mwc-random/0.8.0.2/mwc-random-0.8.0.2.tar.gz:5d95ec60ac4dd4097a4ce23f0e29254a):(darcs:http://src.seereason.com/haskell-mwc-random-debian)"
             , sourceSpec = "apt:sid:haskell-mwc-random"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-network"
             , sourceSpec = "apt:sid:haskell-network"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-pandoc-types"
             , sourceSpec = "apt:sid:haskell-pandoc-types"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-parallel"
             , sourceSpec = "apt:sid:haskell-parallel"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-parsec2"
             , sourceSpec = "apt:sid:haskell-parsec2"
             -- , sourceSpec = "quilt:(apt:sid:haskell-parsec2):(darcs:http://src.seereason.com/haskell-parsec2-quilt)"
             , relaxInfo = [] }
    -- Binary packages: libghc6-quickcheck2-dev, libghc6-quickcheck2-prof, libghc6-quickcheck2-doc
    , Target { sourcePackageName = "haskell-parsec"
             , sourceSpec = "apt:sid:haskell-parsec"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-pcre-light"
             , sourceSpec = "apt:sid:haskell-pcre-light"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-polyparse"
             , sourceSpec = "apt:sid:haskell-polyparse"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-primitive"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/primitive/0.3.1/primitive-0.3.1.tar.gz:9f3a9ecd184a1e1ec5980c66f63e6187):(darcs:http://src.seereason.com/haskell-primitive-debian)"
             , sourceSpec = "apt:sid:haskell-primitive"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-quickcheck"
             , sourceSpec = "apt:sid:haskell-quickcheck"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-quickcheck1"
             , sourceSpec = "apt:sid:haskell-quickcheck1"
             -- , sourceSpec = "quilt:(apt:sid:haskell-quickcheck1):(darcs:http://src.seereason.com/haskell-quickcheck1-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-regex-base"
             , sourceSpec = "apt:sid:haskell-regex-base"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-regex-compat"
             , sourceSpec = "apt:sid:haskell-regex-compat"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-regex-posix"
             , sourceSpec = "apt:sid:haskell-regex-posix"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-regex-tdfa"
             , sourceSpec = "apt:sid:haskell-regex-tdfa"
             -- , sourceSpec = "quilt:(apt:sid:haskell-regex-tdfa):(darcs:http://src.seereason.com/haskell-regex-tdfa-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-safe"
             -- , sourceSpec = "quilt:(apt:sid:haskell-safe=0.2-2):(darcs:" ++ repo ++ "/haskell-safe-quilt)"
             , sourceSpec = "apt:sid:haskell-safe"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-semigroups"
             , sourceSpec = "apt:sid:haskell-semigroups"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-sendfile"
             , sourceSpec = "apt:sid:haskell-sendfile"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/sendfile/0.7.2/sendfile-0.7.2.tar.gz:7e59a3c47ead59ad19c72ee1fcef9fa6):(darcs:http://src.seereason.com/haskell-sendfile-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-sha"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/SHA/1.4.1.3/SHA-1.4.1.3.tar.gz:6adbe05bfaf4416c1a7e1ac5e999811e):(darcs:" ++ repo ++ "/haskell-sha-debian)"
             , sourceSpec = "apt:sid:haskell-sha"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-smtpclient"
             , sourceSpec = "apt:sid:haskell-smtpclient"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/SMTPClient/1.0.2/SMTPClient-1.0.2.tar.gz:59b474179c301a08af45c99f85fca224):(darcs:http://src.seereason.com/haskell-smtpclient-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-split"
             , sourceSpec="apt:sid:haskell-split"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-stm"
             , sourceSpec = "apt:sid:haskell-stm"
             , relaxInfo = [] }
    -- Patch to add the bareAttr function and remove the custom show
    -- instance Specify a particular version of xhtml so we can
    -- perhaps eliminate this the next time the upstream package is
    -- revved.
    , Target { sourcePackageName = "haskell-strict-concurrency"
             , sourceSpec = "apt:sid:haskell-strict-concurrency"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/strict-concurrency/0.2.4.1/strict-concurrency-0.2.4.1.tar.gz:1fea3949811b465b79d8790dd06401e9):(darcs:http://src.seereason.com/haskell-strict-concurrency-debian)"
             , relaxInfo = [] }

    , Target { sourcePackageName = "haskell-syb"

             -- , sourceSpec="deb-dir:(uri:http://hackage.haskell.org/packages/archive/syb/0.2.1/syb-0.2.1.tar.gz:f3c0ada9efc0cbb5e1ff219497a0628b):(darcs:http://src.seereason.com/haskell-syb-debian)"
             , sourceSpec="apt:sid:haskell-syb"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-syb-with-class"
             -- , sourceSpec = "quilt:(apt:sid:haskell-syb-with-class):(darcs:http://src.seereason.com/haskell-syb-with-class-quilt)"
             , sourceSpec = "apt:sid:haskell-syb-with-class"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-syb-with-class-instances-text"
             -- , sourceSpec = "deb-dir:(darcs:http://src.seereason.com/syb-with-class-instances-text):(darcs:http://src.seereason.com/syb-with-class-instances-text-debian)"
             , sourceSpec = "apt:sid:haskell-syb-with-class-instances-text"
             , relaxInfo = [] }      
    , Target { sourcePackageName = "haskell-tagged"
             , sourceSpec = "apt:sid:haskell-tagged"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/tagged/0.1.1/tagged-0.1.1.tar.gz:ed9ddfd0d12dfaf136788da8e32c08f8):(darcs:http://src.seereason.com/haskell-tagged-debian)"
             , relaxInfo = [] }
    , Target{ sourcePackageName = "haskell-tagsoup"
            -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/tagsoup/0.11.1/tagsoup-0.11.1.tar.gz:5469453026dff80cd515ba163c41ecfa):(darcs:http://src.seereason.com/haskell-tagsoup-debian)"
            , sourceSpec = "apt:sid:haskell-tagsoup"
            , relaxInfo = [] }
{-
    , Target { sourcePackageName = "haskell-tagsoup"
             , sourceSpec = "apt:sid:haskell-tagsoup"
             , relaxInfo = []
             }
-}
    , Target { sourcePackageName = "haskell-tar"
             , sourceSpec = "apt:sid:haskell-tar"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/tar/0.3.1.0/tar-0.3.1.0.tar.gz:10b54856495f9ef0a42aa270085c7d5e):(darcs:http://src.seereason.com/haskell-tar-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-terminfo"
             , sourceSpec = "apt:sid:haskell-terminfo"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-testpack"
             , sourceSpec = "apt:sid:haskell-testpack"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-texmath"
             , sourceSpec = "apt:sid:haskell-texmath"
             -- , sourceSpec = "quilt:(apt:sid:haskell-texmath):(darcs:http://src.seereason.com/haskell-texmath-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-uniplate"
             , sourceSpec="quilt:(apt:sid:haskell-uniplate):(darcs:http://src.seereason.com/haskell-uniplate-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-unix-compat"
             , sourceSpec = "apt:sid:haskell-unix-compat"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/unix-compat/0.1.2.1/unix-compat-0.1.2.1.tar.gz:6ecfc3922fce2e96922af3a636b061f9):(darcs:http://src.seereason.com/haskell-unix-compat-debian)"
             , relaxInfo = [] }

    , Target { sourcePackageName = "haskell-utility-ht"
             , sourceSpec = "apt:sid:haskell-utility-ht"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/utility-ht/0.0.5.1/utility-ht-0.0.5.1.tar.gz:98dcb042f404378d9071fc6344703386):(darcs:http://src.seereason.com/haskell-utility-ht-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-vector"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/vector/0.7.0.1/vector-0.7.0.1.tar.gz:b0cfeab898384d960f0ad7393e5f955c):(darcs:http://src.seereason.com/haskell-vector-debian)"
             , sourceSpec = "apt:sid:haskell-vector"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-xhtml"
             , sourceSpec = "apt:sid:haskell-xhtml"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-xml"
             , sourceSpec = "apt:sid:haskell-xml"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/xml/1.3.4/xml-1.3.4.tar.gz:841c3a36a0bfb2e46f88448ecc227cad):(darcs:http://src.seereason.com/debian/haskell-xml-debian)"
             , relaxInfo = [] }
    , Target{ sourcePackageName = "haskell-xss-sanitize"
            , sourceSpec = "apt:sid:haskell-xss-sanitize"
            -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/xss-sanitize/0.2.6/xss-sanitize-0.2.6.tar.gz:ebd120843e10b31c71009b022fab233b):(darcs:http://src.seereason.com/haskell-xss-sanitize-debian)"
            , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-zip-archive"
             , sourceSpec = "apt:sid:haskell-zip-archive"
             -- , sourceSpec = "quilt:(apt:sid:haskell-zip-archive):(darcs:http://src.seereason.com/haskell-zip-archive-quilt)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-zlib-bindings"
             , sourceSpec = "apt:sid:haskell-zlib-bindings"
             -- , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/zlib-bindings/0.0.0/zlib-bindings-0.0.0.tar.gz:ced9be9c31f54ad848f58babf1ca2190):(darcs:http://src.seereason.com/haskell-zlib-bindings-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-zlib"
             , sourceSpec = "apt:sid:haskell-zlib"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haxml"
             , sourceSpec = "apt:sid:haxml"
             , relaxInfo = [] }
    , Target { sourcePackageName = "missingh"
             , sourceSpec = "apt:sid:missingh"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-pcre-light"
             , sourceSpec = "apt:sid:haskell-pcre-light"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-configfile"
             , sourceSpec = "apt:sid:haskell-configfile"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-statistics"
             , sourceSpec = "apt:sid:haskell-statistics"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-vector"
             , sourceSpec = "apt:sid:haskell-vector"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-vector-algorithms"
             , sourceSpec = "apt:sid:haskell-vector-algorithms"
             , relaxInfo = [] }
    ]

-- |Waiting to be upgraded to sid version, or waiting until a newer sid version becomes available.
sidWaiting home =
    [ Target { sourcePackageName = "haskell-tls"
             -- http-enumerator 0.3.1 needs older tls, when we can upgrade to 0.6.5.4 we can use the tls in sid.
             -- , sourceSpec = "apt:sid:haskell-tls"
             , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/tls/0.3/tls-0.3.tar.gz:066b7615916243ad4b834e362dce8542):(darcs:http://src.seereason.com/haskell-tls-debian)"
             , relaxInfo = [] }
    -- Waiting for tls 0.7
--    , Target { sourcePackageName = "haskell-tls-extra"
--             , sourceSpec = "apt:sid:haskell-tls-extra"
--             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-certificate"
             -- Sid version is too new for haskell-tls 0.3
             -- , sourceSpec = "apt:sid:haskell-certificate"
             , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/certificate/0.3.2/certificate-0.3.2.tar.gz:17a2c881188033b1f1e57a852e250daf):(darcs:http://src.seereason.com/haskell-certificate-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-asn1-data"
             -- Sid version is too new for haskell-certificate 0.3.2
             -- , sourceSpec = "quilt:(apt:sid:haskell-asn1-data):(darcs:" ++ localRepo home ++ "/haskell-asn1-data-quilt)"
             , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/asn1-data/0.2.2/asn1-data-0.2.2.tar.gz:dfc412f4b1cff907e924dd65ce70c399):(darcs:http://src.seereason.com/haskell-asn1-data-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-wai"
             -- , sourceSpec = "apt:sid:haskell-wai" - sid version is 0.2.2.1-1, too old
             , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/wai/0.3.1/wai-0.3.1.tar.gz:5a777cf08713a55818955ec4d0748622):(darcs:http://src.seereason.com/haskell-wai-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-cgi"
             -- Version in sid is 3001.1.7.4-1, our version is 3001.1.8.2
             -- , sourceSpec = "apt:sid:haskell-cgi"
             , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/cgi/3001.1.8.2/cgi-3001.1.8.2.tar.gz:4092efaf00ac329b9771879f57a95323):(darcs:http://src.seereason.com/haskell-cgi-debian)"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-opengl"
             , sourceSpec="apt:sid:haskell-opengl"
             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-glut"
             , sourceSpec="apt:sid:haskell-glut"
             , relaxInfo = [] }
--  Fails
--    , Target { sourcePackageName = "cdbs"
--             , sourceSpec = "apt:sid:cdbs"
--             , relaxInfo = [] }
    , Target { sourcePackageName = "haskell-pandoc"
             -- Sid version needs cdbs >= 0.4.70~, which I can't seem to build.
             -- , sourceSpec = "apt:sid:pandoc"
             , sourceSpec = "deb-dir:(uri:http://hackage.haskell.org/packages/archive/pandoc/1.5.1.1/pandoc-1.5.1.1.tar.gz:bfccc042ae0cf0901bbca1f87748f969):(darcs:http://src.seereason.com/haskell-pandoc-debian)"
             , relaxInfo = [] }
    ]

nonHaskell home =
    [ Target { sourcePackageName = "bash-completion"
             , sourceSpec = "apt:sid:bash-completion"
             , relaxInfo = [] }
    , Target { sourcePackageName = "geneweb"
             , sourceSpec = "apt:sid:geneweb"
             , relaxInfo = [] }
    , Target { sourcePackageName = "html-xml-utils"
           , sourceSpec = "apt:sid:html-xml-utils"
           , relaxInfo = [] }
    -- This target fails during an arch only build, because it has no architecture dependent files.
    , Target { sourcePackageName = "tinymce"
             , sourceSpec="apt:sid:tinymce"
             , relaxInfo = [] }
    , Target { sourcePackageName = "wordpress"
             , sourceSpec="apt:sid:wordpress"
             , relaxInfo = [] }
    ]
